FROM ubuntu:24.04

RUN apt-get update && apt-get -y install git gradle openjdk-11-jdk gcc libpcsclite-dev libpython3-dev



USER ubuntu

RUN git config --global --add safe.directory /IdeaProjects/FIDO2Applet
